### ISSUE TITLE
Implement a theme switcher or randomizer

### ISSUE THREAD

**Issue by nileshtrivedi** [learn-awesome/learndb#19]

**Comment by prince-ao** [comment]
It would be helpful if you provided information about the css structure.

**Comment by nileshtrivedi** [comment]
Hey @prince-ao 

We use TailwindCSS combined with Shoelace.style components. We have enabled abstract names for colors (like primary, primary-bg, secondary-bg-light etc).

A theme-switcher should be really an independent tool that applies color/typography/spacing palettes to any TailwindCSS project. So, I would prefer building something generic which could be simply used in this project.

I implemented color randomizer already (it shows up only if you're running this project locally). But now that we have a decent default theme, I will close this issue. The idea for such a tool remains useful but that should be an independent project. I've put this in my [idea-tracker here](https://codeberg.org/nilesh/random-ideas/issues/14).
