### ISSUE TITLE
Dark mode is broken

### ISSUE THREAD

**Issue by prince-ao** [learn-awesome/learndb#42]
On the Firefox browser the main background is black and the nav & nav links are both white making the nav link words unreadable. This error does not happen on the chromium browser.
![Screenshot_20220613_142814](https://user-images.githubusercontent.com/80477926/173420732-633d3f5c-7d18-4627-96b5-5bc216736304.png)

**Comment by nileshtrivedi** [comment]
Thanks for reporting. I can see the same issue in Chrome with the OS being in dark-mode.

**Comment by nileshtrivedi** [comment]
A good path here is to implement dark mode as dynamically applied theme. So, we should avoid using Tailwind's `dark:` classes inside the markup.

**Comment by nileshtrivedi** [comment]
Fixed this by disabling dark mode. I'd prefer to implement dark mode as a theme, and to use themes, I think we should [rethink what it means to have a color palette](https://codeberg.org/nilesh/random-ideas/issues/14#issuecomment-468947).
