### ISSUE TITLE
Implement account-based synchronization.

### ISSUE THREAD

**Issue by beedell-roke** [learn-awesome/learndb#80]
Per https://github.com/learn-awesome/learndb/discussions/81#discussion-6120922, I see no indication that my "to read" lists, etcetera, shall be available should I clear my browser data, much less how I shall access them on a different installation.

**Comment by nileshtrivedi** [comment]
Fair point. I will add messaging to make this clear.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/learn-awesome/learndb/issues/80#issuecomment-1906867177

@nileshtrivedi, I agree - that's exactly the service I use instead.

**Comment by nileshtrivedi** [comment]
@RokeJulianLockhart That actually makes you the perfect person to ask this question:

Do you believe this project is worth maintaining and developing? If so, why?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/learn-awesome/learndb/issues/80#issuecomment-1907424186

@nileshtrivedi, I'll be honest - I'm not totally sure it is, considering the amount of work you're going to have to put in to the backend, only to seemingly reinvent what competitors like https://github.com/internetarchive/openlibrary.git and https://github.com/inventaire/inventaire.git (and, to a lesser extent, https://github.com/bookwyrm-social/bookwyrm#about-bookwyrm) provide. However, I believe that its interface isn't something worth losing.

I suggest ascertaining whether you could feasibly use the knowledge you've gained to provide some better filtering abilities to those projects. Alternatively, if that's still inadequate to provide the same level of immediate user-friendliness which this project affords, maybe strip out the bits someone would want to synchronize with an account (like the to read section) and focus upon this merely being a discoverer for the aforelisted platforms.

I hope I've not been too rambly. This is an impressive project.

**Comment by nileshtrivedi** [comment]
@RokeJulianLockhart Thanks. Actually, I wasn't talking about the old project which required a backend, but the current one which is a static site. Even this one still requires curating the collection of learning resources. It's not exactly competing with OpenLibrary/Bookwyrm etc because those are clearly about books and books alone.
